// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SimpleBlocks.Server.Persistence;

#nullable disable

namespace SimpleBlocks.Server.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250423114624_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SimpleBlocks.Server.Domain.Entities.LanguageFileSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BlocksJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LanguageKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SemanticsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LanguageKey")
                        .IsUnique();

                    b.ToTable("LanguageFileSets");
                });
#pragma warning restore 612, 618
        }
    }
}
