services:
  simpleblocks-server:
    build:
      context: ..
      dockerfile: src/SimpleBlocks.Server/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JUDGE0_URL=${JUDGE0_URL}
      - CORS_ORIGINS=${CORS_ORIGINS}
    networks:
      - simpleblocks-network

networks:
  simpleblocks-network:
    driver: bridge 